/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RestoRouteImport } from './routes/_resto'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'
import { Route as RestoDashboardRouteImport } from './routes/_resto/dashboard'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as RestoDashboardSettingsRouteImport } from './routes/_resto/dashboard.settings'
import { Route as RestoDashboardQrCodeRouteImport } from './routes/_resto/dashboard.qr-code'
import { Route as RestoDashboardMenuRouteImport } from './routes/_resto/dashboard.menu'
import { Route as AdminAdminEnseignesRouteImport } from './routes/_admin/admin.enseignes'
import { Route as AdminAdminEnseignesNewRouteImport } from './routes/_admin/admin.enseignes.new'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoRoute = RestoRouteImport.update({
  id: '/_resto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoDashboardRoute = RestoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestoRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const RestoDashboardSettingsRoute = RestoDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RestoDashboardRoute,
} as any)
const RestoDashboardQrCodeRoute = RestoDashboardQrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => RestoDashboardRoute,
} as any)
const RestoDashboardMenuRoute = RestoDashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RestoDashboardRoute,
} as any)
const AdminAdminEnseignesRoute = AdminAdminEnseignesRouteImport.update({
  id: '/enseignes',
  path: '/enseignes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEnseignesNewRoute = AdminAdminEnseignesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminEnseignesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof RestoDashboardRouteWithChildren
  '/menu/$slug': typeof MenuSlugRoute
  '/admin/enseignes': typeof AdminAdminEnseignesRouteWithChildren
  '/dashboard/menu': typeof RestoDashboardMenuRoute
  '/dashboard/qr-code': typeof RestoDashboardQrCodeRoute
  '/dashboard/settings': typeof RestoDashboardSettingsRoute
  '/admin/enseignes/new': typeof AdminAdminEnseignesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof RestoDashboardRouteWithChildren
  '/menu/$slug': typeof MenuSlugRoute
  '/admin/enseignes': typeof AdminAdminEnseignesRouteWithChildren
  '/dashboard/menu': typeof RestoDashboardMenuRoute
  '/dashboard/qr-code': typeof RestoDashboardQrCodeRoute
  '/dashboard/settings': typeof RestoDashboardSettingsRoute
  '/admin/enseignes/new': typeof AdminAdminEnseignesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_resto': typeof RestoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_resto/dashboard': typeof RestoDashboardRouteWithChildren
  '/menu/$slug': typeof MenuSlugRoute
  '/_admin/admin/enseignes': typeof AdminAdminEnseignesRouteWithChildren
  '/_resto/dashboard/menu': typeof RestoDashboardMenuRoute
  '/_resto/dashboard/qr-code': typeof RestoDashboardQrCodeRoute
  '/_resto/dashboard/settings': typeof RestoDashboardSettingsRoute
  '/_admin/admin/enseignes/new': typeof AdminAdminEnseignesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/menu/$slug'
    | '/admin/enseignes'
    | '/dashboard/menu'
    | '/dashboard/qr-code'
    | '/dashboard/settings'
    | '/admin/enseignes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/menu/$slug'
    | '/admin/enseignes'
    | '/dashboard/menu'
    | '/dashboard/qr-code'
    | '/dashboard/settings'
    | '/admin/enseignes/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_resto'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_admin/admin'
    | '/_resto/dashboard'
    | '/menu/$slug'
    | '/_admin/admin/enseignes'
    | '/_resto/dashboard/menu'
    | '/_resto/dashboard/qr-code'
    | '/_resto/dashboard/settings'
    | '/_admin/admin/enseignes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RestoRoute: typeof RestoRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MenuSlugRoute: typeof MenuSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resto': {
      id: '/_resto'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resto/dashboard': {
      id: '/_resto/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RestoDashboardRouteImport
      parentRoute: typeof RestoRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_resto/dashboard/settings': {
      id: '/_resto/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof RestoDashboardSettingsRouteImport
      parentRoute: typeof RestoDashboardRoute
    }
    '/_resto/dashboard/qr-code': {
      id: '/_resto/dashboard/qr-code'
      path: '/qr-code'
      fullPath: '/dashboard/qr-code'
      preLoaderRoute: typeof RestoDashboardQrCodeRouteImport
      parentRoute: typeof RestoDashboardRoute
    }
    '/_resto/dashboard/menu': {
      id: '/_resto/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof RestoDashboardMenuRouteImport
      parentRoute: typeof RestoDashboardRoute
    }
    '/_admin/admin/enseignes': {
      id: '/_admin/admin/enseignes'
      path: '/enseignes'
      fullPath: '/admin/enseignes'
      preLoaderRoute: typeof AdminAdminEnseignesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/enseignes/new': {
      id: '/_admin/admin/enseignes/new'
      path: '/new'
      fullPath: '/admin/enseignes/new'
      preLoaderRoute: typeof AdminAdminEnseignesNewRouteImport
      parentRoute: typeof AdminAdminEnseignesRoute
    }
  }
}

interface AdminAdminEnseignesRouteChildren {
  AdminAdminEnseignesNewRoute: typeof AdminAdminEnseignesNewRoute
}

const AdminAdminEnseignesRouteChildren: AdminAdminEnseignesRouteChildren = {
  AdminAdminEnseignesNewRoute: AdminAdminEnseignesNewRoute,
}

const AdminAdminEnseignesRouteWithChildren =
  AdminAdminEnseignesRoute._addFileChildren(AdminAdminEnseignesRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminEnseignesRoute: typeof AdminAdminEnseignesRouteWithChildren
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminEnseignesRoute: AdminAdminEnseignesRouteWithChildren,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RestoDashboardRouteChildren {
  RestoDashboardMenuRoute: typeof RestoDashboardMenuRoute
  RestoDashboardQrCodeRoute: typeof RestoDashboardQrCodeRoute
  RestoDashboardSettingsRoute: typeof RestoDashboardSettingsRoute
}

const RestoDashboardRouteChildren: RestoDashboardRouteChildren = {
  RestoDashboardMenuRoute: RestoDashboardMenuRoute,
  RestoDashboardQrCodeRoute: RestoDashboardQrCodeRoute,
  RestoDashboardSettingsRoute: RestoDashboardSettingsRoute,
}

const RestoDashboardRouteWithChildren = RestoDashboardRoute._addFileChildren(
  RestoDashboardRouteChildren,
)

interface RestoRouteChildren {
  RestoDashboardRoute: typeof RestoDashboardRouteWithChildren
}

const RestoRouteChildren: RestoRouteChildren = {
  RestoDashboardRoute: RestoDashboardRouteWithChildren,
}

const RestoRouteWithChildren = RestoRoute._addFileChildren(RestoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RestoRoute: RestoRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MenuSlugRoute: MenuSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
